ktor:
  deployment:
    port: $PORT
  application:
    modules:
      - com.jesusdmedinac.bubble.ApplicationKt.module
gemini:
  key: $GEMINI_KEY
firebase:
  database:
    name: $FIREBASE_DATABASE_NAME